version: '3.0'
services:
  broker:
    image: amqp-broker:1.0
    build: ./amqp-broker
    ports: 
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbitmq
    command: '-s'
  stream-processor:
    image: github-event-streamer
    build: ./github-event-streamer
    command: '--maintenance'
  dummy-producer:
    image: dummy-producer
    build: ./dummy-producer
    command: '--server'
  github-event-consumer:
    image: amqp-consumer
    build: ./amqp-consumer
    command: '--server'
    environment:
      - SUBSCRIBE_TOPIC=github-actions-event
  device-event-consumer:
    image: amqp-consumer
    build: ./amqp-consumer
    command: '--server'
    environment:
      - SUBSCRIBE_TOPIC=device-evnet
